[workspace]
authors = ["David Faden (revfad.com) <dfaden@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "life"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.25.7.0.dev2025100101,<0.26"
python = ">=3.11,<3.13"
rich = ">=14.1.0,<15"
